# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER_MASTER',
            fields=[
                ('USER_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('USERNAME', models.CharField(max_length=40, null=True)),
                ('PASSCODE', models.IntegerField(null=True)),
                ('ORDER_ID', models.IntegerField(null=True)),
            ],
        ),
    ]
